using System;
using System.Runtime.Serialization;

namespace SerialLabs.Data
{
    /// <summary>
    /// Encapsulates any exception generated by the data layer
    /// </summary>
    [SerializableAttribute]
    public class DataException : PlatformException
    {
        /// <summary>
        /// Creates a new instance of the <see cref="DataException"/>
        /// </summary>
        public DataException()
            : base()
        { }
        /// <summary>
        /// Creates a new instance of the <see cref="DataException"/>
        /// </summary>
        /// <param name="message"></param>
        public DataException(string message)
            : base(message)
        { }
        /// <summary>
        /// Creates a new instance of the <see cref="DataException"/>
        /// </summary>
        /// <param name="message"></param>
        /// <param name="innerException"></param>
        public DataException(string message, Exception innerException)
            : base(message, innerException)
        { }
        /// <summary>
        /// Creates a new instance of the <see cref="DataException"/>
        /// </summary>
        /// <param name="info"></param>
        /// <param name="context"></param>
        public DataException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        { }

    }
}
