using System;
using System.Runtime.Serialization;

namespace SerialLabs
{
    /// <summary>
    /// Encapsulates any exception generated by serial-labs platform.
    /// </summary>
    [SerializableAttribute]
    public class PlatformException : Exception
    {
        /// <summary>
        /// Creates a new instance of the <see cref="PlatformException"/>
        /// </summary>
        public PlatformException()
            : base()
        { }
        /// <summary>
        /// Creates a new instance of the <see cref="PlatformException"/>
        /// </summary>
        /// <param name="message"></param>
        public PlatformException(string message)
            : base(message)
        { }
        /// <summary>
        /// Creates a new instance of the <see cref="PlatformException"/>
        /// </summary>
        /// <param name="message"></param>
        /// <param name="innerException"></param>
        public PlatformException(string message, Exception innerException)
            : base(message, innerException)
        { }
        /// <summary>
        /// Creates a new instance of the <see cref="PlatformException"/>
        /// </summary>
        /// <param name="info"></param>
        /// <param name="context"></param>
        public PlatformException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        { }

    }
}
